spring.datasource.url=jdbc:mysql://localhost:3306/reservas_db
spring.datasource.username=root
spring.datasource.password=${MYSQL_PASSWORD:Reservas123!}

jwt.secret=${JWT_SECRET:miClaveSecretaParaElProyectoDeReservasLab2026Segura}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.springframework.security=DEBUG